---
- name: download installer.sh
  sudo : yes
  get_url: >
    url={{anaconda_installer_url}}
    dest=/tmp/{{anaconda_installer_sh}}
    owner=root
    group=root
    mode=751
    use_proxy=yes

- name: install anconda
  sudo: yes
  command: /tmp/{{anaconda_installer_sh}} -b -p /opt/{{anaconda_name}}
  args:
    creates: /opt/{{anaconda_name}}/bin/conda

- name: remove installer.sh
  sudo : yes
  file:
    path=/tmp/{{anaconda_installer_sh}}
    state=absent

- name: link anaconda
  sudo: yes
  file:
    dest=/opt/anaconda
    src=/opt/{{anaconda_name}}
    state=link
    owner=root
    group=root

